
GET {{localhost}}/todos


###
POST {{localhost}}/
Content-Type: application/json
{
    "title": "sdkfjl",
    "dueAt": "2020-04-20",
    "createdBy" : "user3"
}

### Delete Request
DELETE {{localhost}}/todos/3

###
DELETE {{localhost}}/todos/1

###
PUT {{localhost}}/todos/5
Content-Type: application/json

{
  "id": 1,
  "title": "3 st todo update",
  "description": "Updated 3",
  "createdAt": "2020-04-22T16:40:41.467+0000",
  "dueAt": "2020-04-22T16:40:41.467+0000",
  "createdBy": "user123"
}